In [ ]:
###numpy indexing - selecting elements or group of elements from a numpy array

In [2]:
import numpy as np

In [ ]:
arr1= np.arange(25)
arr1

In [ ]:
### reshape method -  here arr array is reshaped from 25 to 5 X 5 matrix

arr1.reshape(5,5)

In [ ]:
######################### INDEXING AND SELECTION ON NUMPY ARRAYS

In [ ]:
vararr = np.arange(0,11)

In [ ]:
vararr

In [ ]:
###to select elements from an np array
vararr[7]

In [ ]:
vararr[1:5]          ### selects 1 thru 4

In [ ]:
vararr[0:]             ### starts at 0 and gets the rest of the np array

In [ ]:
vararr[5:]             ### starts at 5 and gets the rest of the np array. similar to slicing
                      ### grabs everything beyond index 5 because index 5 is 4. 

In [ ]:
##### broadcasting
vararr[0:5] = 100
vararr

In [ ]:
vararr = np.arange(0,11)
vararr


In [ ]:

slice_of_vararr = vararr[0:6]
slice_of_vararr

In [ ]:
slice_of_vararr[:] = 99

In [ ]:
slice_of_vararr   #### please note change also occurs in the original array and not just on slice. avoids memomryissues by not having too many copies of array

In [ ]:
vararr    #### please note change also occurs in the original array and not just on slice

In [ ]:
vararr_copy = vararr.copy()
vararr

In [ ]:
vararr_copy

In [ ]:
vararr_copy[:] = 150

In [ ]:
vararr_copy

In [ ]:
vararr              ###3 original array not impacted. only copy

In [ ]:
#### CONDITIONS WITH NUMPY ARRAYS

In [96]:
arrcond = np.arange(1,11)

In [ ]:
arrcond

In [97]:
arrcond > 5         ####3 i get an output of boolean values

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [ ]:
bool_array = arrcond>5

In [ ]:
arrcond[bool_array]   ####3 will only return instances when the boolean array is true

In [98]:
### to do all in one step will give the same result as above
arrcond[arrcond>5]

array([ 6,  7,  8,  9, 10])

In [99]:
#### to find all elements of array that are odd
arrcond[(arrcond%2 != 0)]

array([1, 3, 5, 7, 9])

In [ ]:
##### the above notation is useful when we start working with pandas

In [100]:
my_new_data = np.arange(25)

In [101]:
my_new_data

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [102]:
my_new_data.shape

(25,)

In [103]:
my_new_data1= my_new_data.reshape(5,5)

In [22]:
### extracting row 1
print(my_new_data1)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [104]:
#### two formats to grabbing data from a matrix
#### double bracket format
####### arrayname[rownumber][colnumber]
#### if i have to grab the data "0" which is 1st row and 1st column in the matrix
my_new_data1[0][0]


### remember the index of 1st row and 1st column is 0 and 0

0

In [24]:
#### to retrieve the entire first row, just give the index of fist row
my_new_data1[0]

array([0, 1, 2, 3, 4])

In [36]:
#### to retrieve the entire first column, just give the index of fist column
my_new_data1[3][0]

15

In [37]:
#### alternate (Recommended) format

In [105]:
### to retrieve the number 9 
### my_new_data1[row1, col4]
my_new_data1[1,4]

9

In [46]:
my_new_data1[1][4]

9

In [47]:
my_new_data1

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [61]:
### to retrieve sections of 2d array- using slice notations
### let us say we want to grab 2,3,4, 7,8,9
##my_new_data1[:5]


array([ 0,  5, 10, 15, 20])

In [68]:
print(my_new_data1)
print('/n')
### extracting first row
my_new_data1[:1]

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
/n


array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [69]:
print(my_new_data1)
print('/n')
### extracting first 2 rows
my_new_data1[:2]

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
/n


array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [70]:
print(my_new_data1)
print('/n')
### extracting all 5 rows
my_new_data1[:4]

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
/n


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [87]:
print(my_new_data1)
print('/n')
### extracting first column
####  :5 - start with row in index 0 and go till index 4+1 () but not included in results)
#### 0:1 - start with column in index 0 and go till index 0+1 but not included in results
my_new_data1[:5,0:1]

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
/n


array([[ 0],
       [ 5],
       [10],
       [15],
       [20]])

In [89]:
print(my_new_data1)
print('/n')
### extracting second column
#### :5 - start with row in index 0 and go till index 4+1 () but not included in results)
#### 0:2 - start with column in index 1 and go till index 1+! but not included in results
my_new_data1[:5,1:2]

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
/n


array([[ 1],
       [ 6],
       [11],
       [16],
       [21]])

In [106]:
print(my_new_data1)
print('/n')
### extracting 1st and second  column all rows
#### :5 - start with row in index 0 and go till index 4+1 () but not included in results)
#### 0:2 - 
my_new_data1[:5,0:2]

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
/n


array([[ 0,  1],
       [ 5,  6],
       [10, 11],
       [15, 16],
       [20, 21]])

In [91]:
print(my_new_data1)
print('/n')
### extracting 2nd(index 1) and third (index 4)rows all columns
#### 2:4 - start with row in index 2 and go till index 3+1 () but not included in results)
#### 0:2 - 
my_new_data1[2:4,0:]

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
/n


array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [93]:
print(my_new_data1)

print('/n')

### extracting 2nd(index 1) and third (index 4)columns all rows
#### 2:4 - start with row in index 2 and go till index 3+1 () but not included in results)
#### 0:2 - 
my_new_data1[:5,1:3]

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
/n


array([[ 1,  2],
       [ 6,  7],
       [11, 12],
       [16, 17],
       [21, 22]])

In [95]:
print(my_new_data1)
print('/n')
### extracting 11, 12 13 16,17,18
#### 2:4 - start with row in index 2 and go till index 3+1 () but not included in results)
#### 0:2 - 
my_new_data1[2:4,1:4]

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
/n


array([[11, 12, 13],
       [16, 17, 18]])